FCC = mpiifort
#FCC = mpif90
#FCC = ftn
MYDIR=/home/ful/Project
DIR_CORE=$(MYDIR)/MPI2D/src/core
DIR_BIN=$(MYDIR)/MPI2D/bin
# Compiler type
 c = intel
# c = gnu

# Compilation Parameters
__FPP = no
__FFT = yes
__OMP = yes
__PROFILE = no
__DEBUG = no
#__DEBUG = yes

ifeq (${c},intel)
   ifeq (${__DEBUG},yes)
      DIR_MOD=$(MYDIR)/MPI2D/src/.mod_debug
      DIR_OBJ=$(MYDIR)/MPI2D/src/.obj_debug
   else
      DIR_MOD=$(MYDIR)/MPI2D/src/.mod
      DIR_OBJ=$(MYDIR)/MPI2D/src/.obj
   endif
else
   ifeq (${__DEBUG},yes)
      DIR_MOD=$(MYDIR)/MPI2D/src/.mod_debug_gnu
      DIR_OBJ=$(MYDIR)/MPI2D/src/.obj_debug_gnu
   else
      DIR_MOD=$(MYDIR)/MPI2D/src/.mod_gnu
      DIR_OBJ=$(MYDIR)/MPI2D/src/.obj_gnu
   endif
endif

# Use FFTW library?
#-I$(FFTW)/include
#/home/ful/soft/fftw-3.3.2
#-L$(FFTW)/lib -lfftw3f
ifeq (${__FFT},yes)
   FFTW=/home/ful/software/fftw-3.3.2
   INCFFT = -I$(FFTW)/include
   LIBFFT = -L$(FFTW)/lib -lfftw3f
else
   INCFFT =
   LIBFFT =
endif

# Use gprof for profiling?
ifeq (${__PROFILE},yes)
   FLAGPROF = -pg
else
   FLAGPROF =
endif

ifeq (${c},intel)
   # Use OpenMP?
   ifeq (${__OMP},yes)
      #FLAGOMP = -openmp
      FLAGOMP = -qopenmp
   else
      FLAGOMP =
   endif
   # Use Fortran preprocessor?
   ifeq (${__FPP},yes)
      FLAGFPP = -fpp -DINTEL_COMPILER
   else
      FLAGFPP =
   endif
   # Use Line Debug?
   ifeq (${__DEBUG},yes)
     # FLAGDEBUG = -traceback -g -check bounds -DDEBUG -check all -O2 -stand f03 -warn all -fstack-protector -assume protect_parens -implicitnone# -assume realloc_lhs
      FLAGDEBUG = -traceback -g -check bounds -DDEBUG -O0 -fp-stack-check -fpe0  
   else
      FLAGDEBUG = -O3 #-assume realloc_lhs 
   endif
   F90FLAGS = -limf -lm $(INCFFT) $(FLAGPROF) $(FLAGOMP) $(FLAGFPP) $(FLAGDEBUG) -assume byterecl -heat-arrays -c -module $(DIR_MOD) -I$(DIR_MOD)

   #LDFLAGS  = -limf -lm $(LIBFFT) $(FLAGPROF) $(FLAGOMP) $(FLAGDEBUG)
   LDFLAGS  = -limf -lm $(LIBFFT) -L../Libhilb  -lhilbert $(FLAGPROF) $(FLAGOMP) $(FLAGDEBUG)
endif

ifeq (${c},gnu)
   # Use OpenMP?
   ifeq (${__OMP},yes)
      FLAGOMP = -fopenmp
   else
      FLAGOMP =
   endif

   # Use Fortran preprocessor?
   ifeq (${__FPP},yes)
      FLAGFPP = -cpp -DGNU_COMPILER
   else
      FLAGFPP =
   endif

   # Use Line Debug?
   ifeq (${__DEBUG},yes)
      FLAGDEBUG = -fbounds-check -lmcheck
   else
      FLAGDEBUG =
   endif
   F90FLAGS =-O3 -w $(INCFFT) $(FLAGPROF) $(FLAGOMP) $(FLAGFPP) $(FLAGDEBUG) -c -funroll-loops -J$(DIR_MOD)
   LDFLAGS  =-O3 -w $(LIBFFT) $(FLAGPROF) $(FLAGOMP) $(FLAGDEBUG)
endif

