#!/bin/bash
#PBS -N fwi_badini_4-50Hz
##PBS -l nodes=2:ppn=40
##PBS -l nodes=seislab2:ppn=78+seislab4:ppn=38
#PBS -l nodes=seislab4:ppn=38+seislab6:ppn=78
#PBS -l walltime=200:00:00

cd $PBS_O_WORKDIR

EXE=/home/ful/project/MPI2D/bin

mod_dir=Marmous_284x461x10

#job=a2d_modeling.x
#parfile=parfile_a2dmod.sh

job=fwi2d_ms_Volve.x
parfile=parfile_fwi_ms.sh

#job=PhaInv2d_Field_2dfft.x
#parfile=parfile_phainv.sh

echo my job is $PBS_JOBID

NP=$(wc -l < $PBS_NODEFILE)
echo NP = $NP
cat $PBS_NODEFILE | uniq -c | awk '{ printf("%s:%s\n", $2, $1); }' > nodelists

#  cmplr=gnu # gnu | intel

#  NETCDF_HOME=/public/software/netcdf-${cmplr}
#  export LD_LIBRARY_PATH=${NETCDF_HOME}/lib:$LD_LIBRARY_PATH
date

/public/software/intel/impi/2017.3.196/bin64/mpirun  -np $NP -machinefile nodelists $EXE/${job} par=/home/ful/project/MPI2D/working/2D_models/${mod_dir}/${parfile} &

wait
date
