DIR_BIN=/home/ful/Project/MPI2D/bin
__OMP = no

# mpi parameter, n -- number of process,
n =20
#n = 1
 
# mpi & opemmp parameters, ppp -- cpus per process
ppp =  1
ifeq (${__OMP},yes)
   RUN = export OMP_NUM_THREADS=${ppp}; mpirun -n ${n} --cpus-per-proc ${ppp} -bysocket -bind-to-socket
  # RUN =  
else #only mpi
   RUN = mpirun -n ${n} 
endif   

# DIR_CURRENT
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/4layers_cmp_121x201x10
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/Twolayer_61x601x1
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/Twolayer_151x201x10
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/Marmous_51x201x10
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/Marmous_243x767x10
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/Marmous_ocean_260x767x10
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/SEG_Salt_201x676x10
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/Baldplate_402x3008x6.25
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/seegsbee_251x601x10
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/2layers_101x201x10_1s1r
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/2layers_circle_101x201x10
#DIR_CURRENT=/home/ful/PhaInv_SeisF90/working/2D_models/mlayer_201x801x10
#DIR_CURRENT=/home/ful/Project/MPI2D/working/2D_models/Marmous_284x461x10
#DIR_CURRENT=/home/ful/Project/MPI2D/working/2D_models/Healthy_trunk_241x241_0.005
#DIR_CURRENT=/home/ful/Project/MPI2D/working/2D_models/Rot_trunk_241x241_0.005
DIR_CURRENT=/home/ful/Project/MPI2D/working/2D_models/Tree6611_200x200_0.006
#DIR_CURRENT=/home/ful/Project/MPI2D/working/2D_models/Simple_Trunk_241x241_0.005

